import Link from 'next/link'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <nav className="border-b px-6 py-3 flex items-center justify-between">
        <Link href="/" className="font-semibold text-lg">ProposalCraft</Link>
      </nav>

      <main className="max-w-2xl mx-auto px-6 py-16">
        <div className="mb-10">
          <h1 className="text-3xl font-bold tracking-tight mb-2">Terms of Service</h1>
          <p className="text-sm text-muted-foreground">Last updated: June 2026</p>
        </div>

        <div className="space-y-8">
          <section>
            <h2 className="text-lg font-semibold mb-2">Using ProposalCraft</h2>
            <p className="text-muted-foreground leading-relaxed">
              ProposalCraft generates AI-powered freelance proposals to help you respond to job postings faster. You are responsible for reviewing and editing proposals before sending them to clients. Do not submit AI-generated content without reviewing it.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">Free plan</h2>
            <p className="text-muted-foreground leading-relaxed">
              Free accounts receive 3 proposals per month. Unused proposals reset at the start of each calendar month and do not roll over.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">Pro plan</h2>
            <p className="text-muted-foreground leading-relaxed">
              Pro accounts are billed at $9/month (or equivalent local currency). You may cancel at any time — cancellation takes effect at the end of your current billing period. We do not offer refunds for partial months.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">Acceptable use</h2>
            <p className="text-muted-foreground leading-relaxed">
              Do not use ProposalCraft to generate spam, misleading content, or proposals for fraudulent job applications. Accounts found violating this policy will be terminated without refund.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">Limitation of liability</h2>
            <p className="text-muted-foreground leading-relaxed">
              ProposalCraft is provided as-is. We are not responsible for outcomes resulting from proposals generated by the service, including rejected applications or client disputes.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">Contact</h2>
            <p className="text-muted-foreground leading-relaxed">
              Questions?{' '}
              <a href="mailto:singh2697.bs@gmail.com" className="underline">
                singh2697.bs@gmail.com
              </a>
            </p>
          </section>
        </div>
      </main>
    </div>
  )
}
